
language: java
jdk:
  - oraclejdk8
# skip installation step
sudo: true
before_script:
- sudo apt-get install tightvncserver
- sudo apt-get install expect

install: true
script:
- bash initDisplay.sh mvn -f AeConverter/pom.xml clean verify coveralls:report