
language: java
# skip installation step
sudo: true
before_script:
- sudo apt-get install tightvncserver
- sudo apt-get install expect

install: true
script:
- bash initDisplay.sh - mvn -f com.examples.myproject/pom.xml clean verify -Pjacoco-report
coveralls:report